---
title: "c_Iowa_Filtering_CPUE"
author: "Denver Link"
date: "2023-11-01"
output: html_document
editor_options: 
  chunk_output_type: console
---

#Library
```{r}
library(tidyverse)
library(arrow)
```

#data
```{r}
ia_data <- open_dataset(sources = file.path("D:", "Shared drives", "Hansen Lab", "RESEARCH PROJECTS", "Fish Survey Data", "Parquet files", "hive"), partitioning = c("state")) %>% 
  filter(state == "Iowa")
glimpse(ia_data)
```

#filtering walleye
```{r}
filter_table_effort <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSkGZinLPrSuv1DorBrAkV2JNUZsOlpG7jk_WsnGyZX56z9JMVcGHdCPlsxInjOdjUH0tXb4nBwt9Js/pub?output=csv") %>% 
  filter(metric == "adult_abundance" & state == "Iowa" & species_1 == "walleye")  %>% 
  select(-metric,
         -survey_type,
         -species_1,
         -water_temp_min,
         -water_temp_max,
         -area_group) %>% 
  rename(sampling_method_2 = sampling_method)

good_surveys <- ia_data %>% 
  #creating a y or n for if we could even expect the species to be present in the survey
  mutate(species_included = case_when(grepl("walleye", target_species, ignore.case = T) | is.na(target_species) ~ "y",
                                      TRUE ~ "n")) %>% 
  #filter for good survey type
  mutate(survey_type_filter = case_when(survey_type %in% c("General", 
                                                           "Comprehensive", 
                                                           "Trend") ~ "y", 
                              TRUE ~ "n")) %>%
  right_join(filter_table_effort, by = c("state",
                                         "sampling_method_2")) %>% 
  distinct(total_effort_ident,
           sampling_method_2,
           date_total_effort_ident,
           total_effort_1,
           effort_min,
           effort_max,
           month_min,
           month_max,
           species_included,
           survey_type_filter) %>% 
  filter(total_effort_1 >= effort_min,
         total_effort_1 <= effort_max,
        month(date_total_effort_ident) >= month_min,
        month(date_total_effort_ident) <= month_max,
        (species_included == "y" & survey_type_filter == "y")) %>% 
  collect()

#collecting fish from good surveys
adult_walleye <- ia_data %>% 
  right_join(good_surveys) %>% 
  collect() %>% 
  #removing one survey that had na and lmb targeted species values at the species level (not survey level)
  group_by(total_effort_ident) %>% 
  filter(n_distinct(target_species) == 1) %>% 
  #remove sub sample surveys that caught nothing but total effort did - generates NAs in cpe calc
  #the effort is still accounted for in the total effort
  filter(!(total_effort_nothing_caught == "FALSE" & sub_effort_nothing_caught == "TRUE"))

#creating cpue for species of interest
adult_walleye_cpue <- adult_walleye %>% 
  #grouping by variables to get survey fish count 
  group_by(total_effort_ident) %>% 
  #counts fish of a particular species in a survey 
  mutate(count = sum(species_1 == 'walleye')) %>% 
  #surveys that did not catch fish (species column is na) return a catch of 0
  mutate(count = case_when(total_effort_nothing_caught == "TRUE" ~ 0,
                           TRUE ~ count)) %>% 
  #generates cpue from counts and efforts associated with that survey count
  mutate(cpue = count/total_effort_1) %>%
  #collapse data into survey level cpue (also works as a select function)
  distinct(total_effort_ident, .keep_all = T) 


#checking filtering
#month range
good_surveys %>% 
  group_by(sampling_method_2) %>% 
  summarise(min.month = min(month(date_total_effort_ident)),
            max.month = max(month(date_total_effort_ident)), 
            min.effort = min(total_effort_1),
            max.effort = max(total_effort_1),
            n = n())

good_surveys %>% 
  group_by(survey_type_filter, species_included) %>% 
  count() 

#is each sampling method correct for the filter?
adult_walleye %>% 
  group_by(sampling_method_2) %>% 
  summarise(min.month = min(month(date_total_effort_ident)),
            max.month = max(month(date_total_effort_ident)), 
            min.effort = min(total_effort_1),
            max.effort = max(total_effort_1),
            n = n())

adult_walleye %>% 
  distinct(total_effort_ident,target_species, species_included,survey_type, survey_type_filter) %>%
  group_by(target_species, species_included,survey_type, survey_type_filter) %>% 
   collect() %>% 
   count() 

#do I retain all of the good surveys? - rows here should match good surveys 
adult_walleye %>% 
  distinct(total_effort_ident,
           sampling_method_2,
           date_total_effort_ident,
           total_effort_1,
           effort_min,
           effort_max,
           month_min,
           month_max,
           species_included,
           survey_type_filter,
           target_species) %>% 
  glimpse()

adult_walleye %>% 
  distinct(total_effort_ident,
           date_total_effort_ident) %>% 
  glimpse()

adult_walleye %>% 
  distinct(total_effort_ident) %>% 
  glimpse()

#range of cpues?
adult_walleye_cpue %>% 
  group_by(sampling_method_2) %>% 
  summarise(min = min(cpue), max = max(cpue))

#any na cpue?
adult_walleye_cpue %>% 
  filter(is.na(cpue)) 

rm(adult_walleye)
```

#filtering black crappie
```{r}
filter_table_effort <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSkGZinLPrSuv1DorBrAkV2JNUZsOlpG7jk_WsnGyZX56z9JMVcGHdCPlsxInjOdjUH0tXb4nBwt9Js/pub?output=csv") %>% 
  filter(metric == "adult_abundance" & state == "Iowa" & species_1 == "black_crappie")  %>% 
  select(-metric,
         -survey_type,
         -species_1,
         -water_temp_min,
         -water_temp_max,
         -area_group) %>% 
  rename(sampling_method_2 = sampling_method)

good_surveys <- ia_data %>% 
  #creating a y or n for if we could even expect the species to be present in the survey
  mutate(species_included = case_when(grepl("black crappie", target_species, ignore.case = T) | is.na(target_species) ~ "y",
                                      TRUE ~ "n")) %>% 
  #filter for good survey type
  mutate(survey_type_filter = case_when(survey_type %in% c("General", 
                                                           "Comprehensive", 
                                                           "Trend") ~ "y", 
                              TRUE ~ "n")) %>%
  right_join(filter_table_effort, by = c("state",
                                         "sampling_method_2")) %>% 
  distinct(total_effort_ident,
           sampling_method_2,
           date_total_effort_ident,
           total_effort_1,
           effort_min,
           effort_max,
           month_min,
           month_max,
           species_included,
           survey_type_filter) %>% 
  filter(total_effort_1 >= effort_min,
         total_effort_1 <= effort_max,
        month(date_total_effort_ident) >= month_min,
        month(date_total_effort_ident) <= month_max,
        (species_included == "y" & survey_type_filter == "y")) %>% 
  collect()

#collecting fish from good surveys
adult_black_crappie <- ia_data %>% 
  right_join(good_surveys) %>% 
  collect() %>% 
  #removing one survey that had na and lmb targeted species values at the species level (not survey level)
  group_by(total_effort_ident) %>% 
  filter(n_distinct(target_species) == 1) %>% 
  filter(!(total_effort_nothing_caught == "FALSE" & sub_effort_nothing_caught == "TRUE"))

#creating cpue for species of interest
adult_black_crappie_cpue <- adult_black_crappie %>% 
  #grouping by variables to get survey fish count 
  group_by(total_effort_ident) %>% 
  #counts fish of a particular species in a survey 
  mutate(count = sum(species_1 == 'black_crappie')) %>% 
  #surveys that did not catch fish (species column is na) return a catch of 0
  mutate(count = case_when(total_effort_nothing_caught == "TRUE" ~ 0,
                           TRUE ~ count)) %>% 
  #generates cpue from counts and efforts associated with that survey count
  mutate(cpue = count/total_effort_1) %>%
  #collapse data into survey level cpue (also works as a select function)
  distinct(total_effort_ident, .keep_all = T) 

#checking filtering
#month range
good_surveys %>% 
  group_by(sampling_method_2) %>% 
  summarise(min.month = min(month(date_total_effort_ident)),
            max.month = max(month(date_total_effort_ident)), 
            min.effort = min(total_effort_1),
            max.effort = max(total_effort_1),
            n = n())

good_surveys %>% 
  group_by(survey_type_filter, species_included) %>% 
  count() 

#is each sampling method correct for the filter?
adult_black_crappie %>% 
  group_by(sampling_method_2) %>% 
  summarise(min.month = min(month(date_total_effort_ident)),
            max.month = max(month(date_total_effort_ident)), 
            min.effort = min(total_effort_1),
            max.effort = max(total_effort_1),
            n = n())

adult_black_crappie %>% 
  distinct(total_effort_ident,target_species, species_included,survey_type, survey_type_filter) %>%
  group_by(target_species, species_included,survey_type, survey_type_filter) %>% 
   collect() %>% 
   count() 

#do I retain all of the good surveys? - rows here should match good surveys 
adult_black_crappie %>% 
  distinct(total_effort_ident,
           sampling_method_2,
           date_total_effort_ident,
           total_effort_1,
           effort_min,
           effort_max,
           month_min,
           month_max,
           species_included,
           survey_type_filter,
           target_species) %>% 
  glimpse()

adult_black_crappie %>% 
  distinct(total_effort_ident,
           date_total_effort_ident) %>% 
  glimpse()

adult_black_crappie %>% 
  distinct(total_effort_ident) %>% 
  glimpse()

#range of cpues?
adult_black_crappie_cpue %>% 
  group_by(sampling_method_2) %>% 
  summarise(min = min(cpue), max = max(cpue))

#any na cpue?
adult_black_crappie_cpue %>% 
  filter(is.na(cpue)) 

rm(adult_black_crappie)
```

#filtering bluegill
```{r}
filter_table_effort <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSkGZinLPrSuv1DorBrAkV2JNUZsOlpG7jk_WsnGyZX56z9JMVcGHdCPlsxInjOdjUH0tXb4nBwt9Js/pub?output=csv") %>% 
  filter(metric == "adult_abundance" & state == "Iowa" & species_1 == "bluegill")  %>% 
  select(-metric,
         -survey_type,
         -species_1,
         -water_temp_min,
         -water_temp_max,
         -area_group) %>% 
  rename(sampling_method_2 = sampling_method)

good_surveys <- ia_data %>% 
  #creating a y or n for if we could even expect the species to be present in the survey
  mutate(species_included = case_when(grepl("bluegill", target_species, ignore.case = T) | is.na(target_species) ~ "y",
                                      TRUE ~ "n")) %>% 
  #filter for good survey type
  mutate(survey_type_filter = case_when(survey_type %in% c("General", 
                                                           "Comprehensive", 
                                                           "Trend") ~ "y", 
                              TRUE ~ "n")) %>%
  right_join(filter_table_effort, by = c("state",
                                         "sampling_method_2")) %>% 
  distinct(total_effort_ident,
           sampling_method_2,
           date_total_effort_ident,
           total_effort_1,
           effort_min,
           effort_max,
           month_min,
           month_max,
           species_included,
           survey_type_filter) %>% 
  filter(total_effort_1 >= effort_min,
         total_effort_1 <= effort_max,
        month(date_total_effort_ident) >= month_min,
        month(date_total_effort_ident) <= month_max,
        (species_included == "y" & survey_type_filter == "y")) %>% 
  collect()

#collecting fish from good surveys
adult_bluegill <- ia_data %>% 
  right_join(good_surveys) %>% 
  collect() %>% 
  #removing one survey that had na and lmb targeted species values at the species level (not survey level)
  group_by(total_effort_ident) %>% 
  filter(n_distinct(target_species) == 1) %>% 
  filter(!(total_effort_nothing_caught == "FALSE" & sub_effort_nothing_caught == "TRUE"))

#creating cpue for species of interest
adult_bluegill_cpue <- adult_bluegill %>% 
  #grouping by variables to get survey fish count 
  group_by(total_effort_ident) %>% 
  #counts fish of a particular species in a survey 
  mutate(count = sum(species_1 == 'bluegill')) %>% 
  #surveys that did not catch fish (species column is na) return a catch of 0
  mutate(count = case_when(total_effort_nothing_caught == "TRUE" ~ 0,
                           TRUE ~ count)) %>% 
  #generates cpue from counts and efforts associated with that survey count
  mutate(cpue = count/total_effort_1) %>%
  #collapse data into survey level cpue (also works as a select function)
  distinct(total_effort_ident, .keep_all = T) 

#checking filtering
#month range
good_surveys %>% 
  group_by(sampling_method_2) %>% 
  summarise(min.month = min(month(date_total_effort_ident)),
            max.month = max(month(date_total_effort_ident)), 
            min.effort = min(total_effort_1),
            max.effort = max(total_effort_1),
            n = n())

good_surveys %>% 
  group_by(survey_type_filter, species_included) %>% 
  count() 

#is each sampling method correct for the filter?
adult_bluegill %>% 
  group_by(sampling_method_2) %>% 
  summarise(min.month = min(month(date_total_effort_ident)),
            max.month = max(month(date_total_effort_ident)), 
            min.effort = min(total_effort_1),
            max.effort = max(total_effort_1),
            n = n())

adult_bluegill %>% 
  distinct(total_effort_ident,target_species, species_included,survey_type, survey_type_filter) %>%
  group_by(target_species, species_included,survey_type, survey_type_filter) %>% 
   collect() %>% 
   count() 

#do I retain all of the good surveys? - rows here should match good surveys 
adult_bluegill %>% 
  distinct(total_effort_ident,
           sampling_method_2,
           date_total_effort_ident,
           total_effort_1,
           effort_min,
           effort_max,
           month_min,
           month_max,
           species_included,
           survey_type_filter,
           target_species) %>% 
  glimpse()

adult_bluegill %>% 
  distinct(total_effort_ident,
           date_total_effort_ident) %>% 
  glimpse()

adult_bluegill %>% 
  distinct(total_effort_ident) %>% 
  glimpse()

#range of cpues?
adult_bluegill_cpue %>% 
  group_by(sampling_method_2) %>% 
  summarise(min = min(cpue), max = max(cpue))
#an efishing value has an effort of 0?

#any na cpue?
adult_bluegill_cpue %>% 
  filter(is.na(cpue)) 

rm(adult_bluegill)
```

#filtering largemouth bass
```{r}
filter_table_effort <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSkGZinLPrSuv1DorBrAkV2JNUZsOlpG7jk_WsnGyZX56z9JMVcGHdCPlsxInjOdjUH0tXb4nBwt9Js/pub?output=csv") %>% 
  filter(metric == "adult_abundance" & state == "Iowa" & species_1 == "largemouth_bass")  %>% 
  select(-metric,
         -survey_type,
         -species_1,
         -water_temp_min,
         -water_temp_max,
         -area_group) %>% 
  rename(sampling_method_2 = sampling_method)

good_surveys <- ia_data %>% 
  #creating a y or n for if we could even expect the species to be present in the survey
  mutate(species_included = case_when(grepl("largemouth", target_species, ignore.case = T) | is.na(target_species) ~ "y",
                                      TRUE ~ "n")) %>% 
  #filter for good survey type
  mutate(survey_type_filter = case_when(survey_type %in% c("General", 
                                                           "Comprehensive", 
                                                           "Trend") ~ "y", 
                              TRUE ~ "n")) %>%
  right_join(filter_table_effort, by = c("state",
                                         "sampling_method_2")) %>% 
  distinct(total_effort_ident,
           sampling_method_2,
           date_total_effort_ident,
           total_effort_1,
           effort_min,
           effort_max,
           month_min,
           month_max,
           species_included,
           survey_type_filter) %>% 
  filter(total_effort_1 >= effort_min,
         total_effort_1 <= effort_max,
        month(date_total_effort_ident) >= month_min,
        month(date_total_effort_ident) <= month_max,
        (species_included == "y" & survey_type_filter == "y")) %>% 
  collect()

#collecting fish from good surveys
adult_largemouth_bass <- ia_data %>% 
  right_join(good_surveys) %>% 
  collect() %>% 
  #removing one survey that had na and lmb targeted species values at the species level (not survey level)
  group_by(total_effort_ident) %>% 
  filter(n_distinct(target_species) == 1) %>% 
  filter(!(total_effort_nothing_caught == "FALSE" & sub_effort_nothing_caught == "TRUE"))

#creating cpue for species of interest
adult_largemouth_bass_cpue <- adult_largemouth_bass %>% 
  #grouping by variables to get survey fish count 
  group_by(total_effort_ident) %>% 
  #counts fish of a particular species in a survey 
  mutate(count = sum(species_1 == 'largemouth_bass')) %>% 
  #surveys that did not catch fish (species column is na) return a catch of 0
  mutate(count = case_when(total_effort_nothing_caught == "TRUE" ~ 0,
                           TRUE ~ count)) %>% 
  #generates cpue from counts and efforts associated with that survey count
  mutate(cpue = count/total_effort_1) %>%
  #collapse data into survey level cpue (also works as a select function)
  distinct(total_effort_ident, .keep_all = T) 

#checking filtering
#month range
good_surveys %>% 
  group_by(sampling_method_2) %>% 
  summarise(min.month = min(month(date_total_effort_ident)),
            max.month = max(month(date_total_effort_ident)), 
            min.effort = min(total_effort_1),
            max.effort = max(total_effort_1),
            n = n())

good_surveys %>% 
  group_by(survey_type_filter, species_included) %>% 
  count() 

#is each sampling method correct for the filter?
adult_largemouth_bass %>% 
  group_by(sampling_method_2) %>% 
  summarise(min.month = min(month(date_total_effort_ident)),
            max.month = max(month(date_total_effort_ident)), 
            min.effort = min(total_effort_1),
            max.effort = max(total_effort_1),
            n = n())

adult_largemouth_bass %>% 
  distinct(total_effort_ident,target_species, species_included,survey_type, survey_type_filter) %>%
  group_by(target_species, species_included,survey_type, survey_type_filter) %>% 
   collect() %>% 
   count() 

#do I retain all of the good surveys? - rows here should match good surveys 
adult_largemouth_bass %>% 
  distinct(total_effort_ident,
           sampling_method_2,
           date_total_effort_ident,
           total_effort_1,
           effort_min,
           effort_max,
           month_min,
           month_max,
           species_included,
           survey_type_filter,
           target_species) %>% 
  glimpse()

adult_largemouth_bass %>% 
  distinct(total_effort_ident,
           date_total_effort_ident) %>% 
  glimpse()

adult_largemouth_bass %>% 
  distinct(total_effort_ident) %>% 
  glimpse()

#range of cpues?
adult_largemouth_bass_cpue %>% 
  group_by(sampling_method_2) %>% 
  summarise(min = min(cpue), max = max(cpue))

#any na cpue?
adult_largemouth_bass_cpue %>% 
  filter(is.na(cpue)) 

rm(adult_largemouth_bass)
```

#filtering smallmouth bass
```{r}
filter_table_effort <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSkGZinLPrSuv1DorBrAkV2JNUZsOlpG7jk_WsnGyZX56z9JMVcGHdCPlsxInjOdjUH0tXb4nBwt9Js/pub?output=csv") %>% 
  filter(metric == "adult_abundance" & state == "Iowa" & species_1 == "smallmouth_bass")  %>% 
  select(-metric,
         -survey_type,
         -species_1,
         -water_temp_min,
         -water_temp_max,
         -area_group) %>% 
  rename(sampling_method_2 = sampling_method)

good_surveys <- ia_data %>% 
  #creating a y or n for if we could even expect the species to be present in the survey
  mutate(species_included = case_when(grepl("smallmouth", target_species, ignore.case = T) | is.na(target_species) ~ "y",
                                      TRUE ~ "n")) %>% 
  #filter for good survey type
  mutate(survey_type_filter = case_when(survey_type %in% c("General", 
                                                           "Comprehensive", 
                                                           "Trend") ~ "y", 
                              TRUE ~ "n")) %>%
  right_join(filter_table_effort, by = c("state",
                                         "sampling_method_2")) %>% 
  distinct(total_effort_ident,
           sampling_method_2,
           date_total_effort_ident,
           total_effort_1,
           effort_min,
           effort_max,
           month_min,
           month_max,
           species_included,
           survey_type_filter) %>% 
  filter(total_effort_1 >= effort_min,
         total_effort_1 <= effort_max,
        month(date_total_effort_ident) >= month_min,
        month(date_total_effort_ident) <= month_max,
        (species_included == "y" & survey_type_filter == "y")) %>% 
  collect()

#collecting fish from good surveys
adult_smallmouth_bass <- ia_data %>% 
  right_join(good_surveys) %>% 
  collect() %>% 
  #removing one survey that had na and lmb targeted species values at the species level (not survey level)
  group_by(total_effort_ident) %>% 
  filter(n_distinct(target_species) == 1) %>% 
  filter(!(total_effort_nothing_caught == "FALSE" & sub_effort_nothing_caught == "TRUE"))

#creating cpue for species of interest
adult_smallmouth_bass_cpue <- adult_smallmouth_bass %>% 
  #grouping by variables to get survey fish count 
  group_by(total_effort_ident) %>% 
  #counts fish of a particular species in a survey 
  mutate(count = sum(species_1 == 'smallmouth_bass')) %>% 
  #surveys that did not catch fish (species column is na) return a catch of 0
  mutate(count = case_when(total_effort_nothing_caught == "TRUE" ~ 0,
                           TRUE ~ count)) %>% 
  #generates cpue from counts and efforts associated with that survey count
  mutate(cpue = count/total_effort_1) %>%
  #collapse data into survey level cpue (also works as a select function)
  distinct(total_effort_ident, .keep_all = T) 

#checking filtering
#month range
good_surveys %>% 
  group_by(sampling_method_2) %>% 
  summarise(min.month = min(month(date_total_effort_ident)),
            max.month = max(month(date_total_effort_ident)), 
            min.effort = min(total_effort_1),
            max.effort = max(total_effort_1),
            n = n())

good_surveys %>% 
  group_by(survey_type_filter, species_included) %>% 
  count() 

#is each sampling method correct for the filter?
adult_smallmouth_bass %>% 
  group_by(sampling_method_2) %>% 
  summarise(min.month = min(month(date_total_effort_ident)),
            max.month = max(month(date_total_effort_ident)), 
            min.effort = min(total_effort_1),
            max.effort = max(total_effort_1),
            n = n())

adult_smallmouth_bass %>% 
  distinct(total_effort_ident,target_species, species_included,survey_type, survey_type_filter) %>%
  group_by(target_species, species_included,survey_type, survey_type_filter) %>% 
   collect() %>% 
   count() 

#do I retain all of the good surveys? - rows here should match good surveys 
adult_smallmouth_bass %>% 
  distinct(total_effort_ident,
           sampling_method_2,
           date_total_effort_ident,
           total_effort_1,
           effort_min,
           effort_max,
           month_min,
           month_max,
           species_included,
           survey_type_filter,
           target_species) %>% 
  glimpse()

adult_smallmouth_bass %>% 
  distinct(total_effort_ident,
           date_total_effort_ident) %>% 
  glimpse()

adult_smallmouth_bass %>% 
  distinct(total_effort_ident) %>% 
  glimpse()

#range of cpues?
adult_smallmouth_bass_cpue %>% 
  group_by(sampling_method_2) %>% 
  summarise(min = min(cpue), max = max(cpue))

#any na cpue?
adult_smallmouth_bass_cpue %>% 
  filter(is.na(cpue)) 

rm(adult_smallmouth_bass)
```

#filtering northern pike
```{r}
filter_table_effort <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSkGZinLPrSuv1DorBrAkV2JNUZsOlpG7jk_WsnGyZX56z9JMVcGHdCPlsxInjOdjUH0tXb4nBwt9Js/pub?output=csv") %>% 
  filter(metric == "adult_abundance" & state == "Iowa" & species_1 == "northern_pike")  %>% 
  select(-metric,
         -survey_type,
         -species_1,
         -water_temp_min,
         -water_temp_max,
         -area_group) %>% 
  rename(sampling_method_2 = sampling_method)

good_surveys <- ia_data %>% 
  #creating a y or n for if we could even expect the species to be present in the survey
  mutate(species_included = case_when(grepl("pike", target_species, ignore.case = T) | is.na(target_species) ~ "y",
                                      TRUE ~ "n")) %>% 
  #filter for good survey type
  mutate(survey_type_filter = case_when(survey_type %in% c("General", 
                                                           "Comprehensive", 
                                                           "Trend") ~ "y", 
                              TRUE ~ "n")) %>%
  right_join(filter_table_effort, by = c("state",
                                         "sampling_method_2")) %>% 
  distinct(total_effort_ident,
           sampling_method_2,
           date_total_effort_ident,
           total_effort_1,
           effort_min,
           effort_max,
           month_min,
           month_max,
           species_included,
           survey_type_filter) %>% 
  filter(total_effort_1 >= effort_min,
         total_effort_1 <= effort_max,
        month(date_total_effort_ident) >= month_min,
        month(date_total_effort_ident) <= month_max,
        (species_included == "y" & survey_type_filter == "y")) %>% 
  collect()

#collecting fish from good surveys
adult_northern_pike <- ia_data %>% 
  right_join(good_surveys) %>% 
  collect() %>% 
  #removing one survey that had na and lmb targeted species values at the species level (not survey level)
  group_by(total_effort_ident) %>% 
  filter(n_distinct(target_species) == 1) %>% 
  filter(!(total_effort_nothing_caught == "FALSE" & sub_effort_nothing_caught == "TRUE"))

#creating cpue for species of interest
adult_northern_pike_cpue <- adult_northern_pike %>% 
  #grouping by variables to get survey fish count 
  group_by(total_effort_ident) %>% 
  #counts fish of a particular species in a survey 
  mutate(count = sum(species_1 == 'northern_pike')) %>% 
  #surveys that did not catch fish (species column is na) return a catch of 0
  mutate(count = case_when(total_effort_nothing_caught == "TRUE" ~ 0,
                           TRUE ~ count)) %>% 
  #generates cpue from counts and efforts associated with that survey count
  mutate(cpue = count/total_effort_1) %>%
  #collapse data into survey level cpue (also works as a select function)
  distinct(total_effort_ident, .keep_all = T) 

#checking filtering
#month range
good_surveys %>% 
  group_by(sampling_method_2) %>% 
  summarise(min.month = min(month(date_total_effort_ident)),
            max.month = max(month(date_total_effort_ident)), 
            min.effort = min(total_effort_1),
            max.effort = max(total_effort_1),
            n = n())

good_surveys %>% 
  group_by(survey_type_filter, species_included) %>% 
  count() 

#is each sampling method correct for the filter?
adult_northern_pike %>% 
  group_by(sampling_method_2) %>% 
  summarise(min.month = min(month(date_total_effort_ident)),
            max.month = max(month(date_total_effort_ident)), 
            min.effort = min(total_effort_1),
            max.effort = max(total_effort_1),
            n = n())

adult_northern_pike %>% 
  distinct(total_effort_ident,target_species, species_included,survey_type, survey_type_filter) %>%
  group_by(target_species, species_included,survey_type, survey_type_filter) %>% 
   collect() %>% 
   count() 

#do I retain all of the good surveys? - rows here should match good surveys 
adult_northern_pike %>% 
  distinct(total_effort_ident,
           sampling_method_2,
           date_total_effort_ident,
           total_effort_1,
           effort_min,
           effort_max,
           month_min,
           month_max,
           species_included,
           survey_type_filter,
           target_species) %>% 
  glimpse()

adult_northern_pike %>% 
  distinct(total_effort_ident,
           date_total_effort_ident) %>% 
  glimpse()

adult_northern_pike %>% 
  distinct(total_effort_ident) %>% 
  glimpse()

#range of cpues?
adult_northern_pike_cpue %>% 
  group_by(sampling_method_2) %>% 
  summarise(min = min(cpue), max = max(cpue))
#an efishing value has an effort of 0?

#any na cpue?
adult_northern_pike_cpue %>% 
  filter(is.na(cpue)) 

rm(adult_northern_pike)
```

#filtering yellow perch
```{r}
filter_table_effort <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSkGZinLPrSuv1DorBrAkV2JNUZsOlpG7jk_WsnGyZX56z9JMVcGHdCPlsxInjOdjUH0tXb4nBwt9Js/pub?output=csv") %>% 
  filter(metric == "adult_abundance" & state == "Iowa" & species_1 == "yellow_perch")  %>% 
  select(-metric,
         -survey_type,
         -species_1,
         -water_temp_min,
         -water_temp_max,
         -area_group) %>% 
  rename(sampling_method_2 = sampling_method)

good_surveys <- ia_data %>% 
  #creating a y or n for if we could even expect the species to be present in the survey
  mutate(species_included = case_when(grepl("perch", target_species, ignore.case = T) | is.na(target_species) ~ "y",
                                      TRUE ~ "n")) %>% 
  #filter for good survey type
  mutate(survey_type_filter = case_when(survey_type %in% c("General", 
                                                           "Comprehensive", 
                                                           "Trend") ~ "y", 
                              TRUE ~ "n")) %>%
  right_join(filter_table_effort, by = c("state",
                                         "sampling_method_2")) %>% 
  distinct(total_effort_ident,
           sampling_method_2,
           date_total_effort_ident,
           total_effort_1,
           effort_min,
           effort_max,
           month_min,
           month_max,
           species_included,
           survey_type_filter) %>% 
  filter(total_effort_1 >= effort_min,
         total_effort_1 <= effort_max,
        month(date_total_effort_ident) >= month_min,
        month(date_total_effort_ident) <= month_max,
        (species_included == "y" & survey_type_filter == "y")) %>% 
  collect()

#collecting fish from good surveys
adult_yellow_perch <- ia_data %>% 
  right_join(good_surveys) %>% 
  collect() %>% 
  #removing one survey that had na and lmb targeted species values at the species level (not survey level)
  group_by(total_effort_ident) %>% 
  filter(n_distinct(target_species) == 1) %>% 
  filter(!(total_effort_nothing_caught == "FALSE" & sub_effort_nothing_caught == "TRUE"))

#creating cpue for species of interest
adult_yellow_perch_cpue <- adult_yellow_perch %>% 
  #grouping by variables to get survey fish count 
  group_by(total_effort_ident) %>% 
  #counts fish of a particular species in a survey 
  mutate(count = sum(species_1 == 'yellow_perch')) %>% 
  #surveys that did not catch fish (species column is na) return a catch of 0
  mutate(count = case_when(total_effort_nothing_caught == "TRUE" ~ 0,
                           TRUE ~ count)) %>% 
  #generates cpue from counts and efforts associated with that survey count
  mutate(cpue = count/total_effort_1) %>%
  #collapse data into survey level cpue (also works as a select function)
  distinct(total_effort_ident, .keep_all = T) 

#checking filtering
#month range
good_surveys %>% 
  group_by(sampling_method_2) %>% 
  summarise(min.month = min(month(date_total_effort_ident)),
            max.month = max(month(date_total_effort_ident)), 
            min.effort = min(total_effort_1),
            max.effort = max(total_effort_1),
            n = n())

good_surveys %>% 
  group_by(survey_type_filter, species_included) %>% 
  count() 

#is each sampling method correct for the filter?
adult_yellow_perch %>% 
  group_by(sampling_method_2) %>% 
  summarise(min.month = min(month(date_total_effort_ident)),
            max.month = max(month(date_total_effort_ident)), 
            min.effort = min(total_effort_1),
            max.effort = max(total_effort_1),
            n = n())

adult_yellow_perch %>% 
  distinct(total_effort_ident,target_species, species_included,survey_type, survey_type_filter) %>%
  group_by(target_species, species_included,survey_type, survey_type_filter) %>% 
   collect() %>% 
   count() 

#do I retain all of the good surveys? - rows here should match good surveys 
adult_yellow_perch %>% 
  distinct(total_effort_ident,
           sampling_method_2,
           date_total_effort_ident,
           total_effort_1,
           effort_min,
           effort_max,
           month_min,
           month_max,
           species_included,
           survey_type_filter,
           target_species) %>% 
  glimpse()

adult_yellow_perch %>% 
  distinct(total_effort_ident,
           date_total_effort_ident) %>% 
  glimpse()

adult_yellow_perch %>% 
  distinct(total_effort_ident) %>% 
  glimpse()

#range of cpues?
adult_yellow_perch_cpue %>% 
  group_by(sampling_method_2) %>% 
  summarise(min = min(cpue), max = max(cpue))

#any na cpue?
adult_yellow_perch_cpue %>% 
  filter(is.na(cpue)) 

rm(adult_yellow_perch)
```

#combining species
```{r}
ia_filtered_species <- bind_rows(adult_walleye_cpue %>% 
                                   mutate(species_1 = "walleye"), 
                                 adult_bluegill_cpue %>% 
                                   mutate(species_1 = "bluegill"), 
                                 adult_black_crappie_cpue %>% 
                                   mutate(species_1 = "black_crappie"),
                                 adult_largemouth_bass_cpue %>% 
                                   mutate(species_1 = "largemouth_bass"), 
                                 adult_smallmouth_bass_cpue %>% 
                                   mutate(species_1 = "smallmouth_bass"), 
                                 adult_northern_pike_cpue %>% 
                                   mutate(species_1 = "northern_pike"), 
                                 adult_yellow_perch_cpue %>% 
                                   mutate(species_1 = "yellow_perch"))
write_csv(ia_filtered_species, "IA_all_cpue_filtered.csv")
```

#data exploration
```{r}
ia_data %>% 
  group_by(sampling_method, total_effort_1_units) %>% 
  count() %>% 
  collect() %>% 
  print( n = nrow(.))

ia_data %>%
  filter(!is.na(total_effort_1)) %>% 
  group_by(sampling_method, total_effort_1_units) %>%
  summarise(min = min(total_effort_1), max = max(total_effort_1), mean = mean(total_effort_1)) %>% 
  collect() %>% 
  print( n = nrow(.))

ia_data %>% 
  filter(is.na(total_effort_1)) %>% 
  group_by(sampling_method) %>% 
  count() %>% 
  collect()


ia_data %>% 
  distinct(total_effort_ident, sampling_method, total_effort_1) %>% 
  filter(total_effort_1 < 500) %>% 
  collect() %>% 
  ggplot() +
  geom_histogram(aes(total_effort_1)) + 
  geom_vline(xintercept = c(24, .5)) +
  facet_wrap(~sampling_method, scales = "free")

ia_data %>% 
  distinct(total_effort_ident, sampling_method, total_effort_1_units) %>% 
  group_by(sampling_method, total_effort_1_units) %>% 
  count() %>% 
  collect() %>%
  arrange(n) %>% 
  print(n = nrow(.))

ia_data %>% 
  distinct(total_effort_ident, sampling_method, total_effort_1) %>% 
  group_by(sampling_method) %>%
  collect() %>% 
  summarise(n = sum(total_effort_1 < 500 & total_effort_1 > .5, na.rm = T)) 
#roughly 1045 efishing, 427 fyke netting, 70 gill netting

ia_data %>% 
  distinct(total_effort_ident, survey_type, sampling_method) %>% 
  group_by(survey_type, sampling_method) %>% 
  count() %>% 
  arrange(n) %>% 
  collect() %>% 
  print(n = nrow(.))

ia_data %>% 
  distinct(total_effort_ident, target_species, survey_type, sampling_method) %>% 
  group_by(target_species, survey_type, sampling_method) %>% 
  count() %>% 
  collect() %>% 
  print(n = nrow(.))

ia_data %>% 
  filter(total_effort_ident == "5748") %>% 
  collect() %>% 
  distinct(total_effort_ident, target_species, .keep_all = T) %>% 
  glimpse()
```

