---
title: "CASC_Data_Explainer_Work"
author: "Holly Kundel"
date: "`r Sys.Date()`"
output: html_document
---

2/2/23
First attempt to use the CASC Data Explainer File to rename columns and create units columns where needed

```{r}
library(readr)
library(readxl)
library(dplyr)
library(stringr)
library(arrow)
library(data.table)
```

Read in CASC Data Explainer
```{r}
CASC_Data_explainer_02Feb23 <- read_csv_arrow("Data_and_Scripts/Data/Data_Explainer/CASC_Data_Explainer_for_R_Data_Manipulation_02Feb23.csv")
  
CASC_Data_explainer <- read_excel("G:/.shortcut-targets-by-id/1eHXdJvNMq46tBKURFTeViKWGdSBhWsL_/Data/CASC_Data_Explainer_for_R_Data_Manipulation.xlsx")
```

Read in MN Data (starting with 2 files)
```{r}
mn_gde_gsh_fish_effort_03May2022 <- read_csv("Data_and_Scripts/Data/Data_Summaries/MN/5.3.22_update/ALL-GDEGSH-SURVEYS.csv")
```

Get new column names from data explainer
```{r}
CDE_cols <- colnames(CASC_Data_explainer_02Feb23) #all possible column names, including garbage column

gde_gsh_col_id <- CASC_Data_explainer_02Feb23 %>% # call data explainer file
  filter(`New File Name`== "mn_gde_gsh_fish_effort_03May2022")%>% #keep only the row relevant to this file
  select_if(~ !any(is.na(.)))%>% #drop columns that contain NA (because that means df doesn't contain that info)
  select(14:25) #keep only columns of relevance (remove our file tracking and urls)
```

The attempts below did NOT work :(
```{r}
# note for files that have items in the "garbage bin" column, we may have a different process where we remove garbage columns after 'filter' but before dropping na columns

old_cols <- (gde_gsh_col_id[1,]) #pulls exisitng column names that are in row 1

new_cols <- data.frame(colnames(gde_gsh_col_id))#pulls column names that have a match in our file of interest 

all_gde_gsh_col <- mn_gde_gsh_fish_effort_03May2022 %>%
  rename(new_cols = old_cols)

renamed_columns <- gde_gsh_col_id %>%
  add_row()

sapply(all_gde_gsh, rename)


#almost works
colnames(all_gde_gsh) <- new_cols
```

#### THIS WORKS


Thanks to this: https://statisticsglobe.com/assign-column-names-based-on-existing-row-in-r


```{R}
gde_gsh_col_id <- CASC_Data_explainer_02Feb23 %>% # call data explainer file
  filter(`New File Name`== "mn_gde_gsh_fish_effort_03May2022")%>% #keep only the row relevant to this file
  select_if(~ !any(is.na(.)))%>% #drop columns that contain NA (because that means df doesn't contain that info)
  select(14:25) #keep only columns of relevance (remove our file tracking and urls)


colnames(all_gde_gsh) <- (colnames(gde_gsh_col_id))
```

```{r}
library(dtplyr)
```







this stuff doesn't work, and contains examples from the internet that failed to help
```{r}
#gde_gsh_col_id[1,i] <- colnames(gde_gsh_col_id)[i]


#all_gde_gsh_col <- mn_gde_gsh_fish_effort_03May2022 %>% rename(all_of(old_cols))


# Rename using a named vector and `all_of()`
lookup <- c(pl = "Petal.Length", sl = "Sepal.Length")
rename(iris, all_of(lookup))


# Using data.table
library(data.table)

# rename all columns for old to new
# Rename columns from list
setnames(my_dataframe, old = c('c1','c2','c3','c4','c5'), 
         new = c('id','pages','name','chapters','price'))
```
